# Пользователи
## Создать нового пользователя

POST http://localhost:6000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "ilkolmakov@mail.ru",
  "avatarPath": "torrance.png",
  "userName": "IlyaK",
  "password": "test123",
  "type": "pro"
}

###

## Авторизовать пользователя

POST http://localhost:6000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "ilkolmakov@yandex.ru",
  "password": "qw12345678"
}

###