# Пользователи

## Показать список избранных предложений

GET  http://localhost:6000/users/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NzI4NzljNmFmY2JmYWY4YjdjNDEzYWIiLCJpYXQiOjE3MzA3OTg2MTAsImV4cCI6MTczMDk3MTQxMH0.ovcfrRHJMTt1np5lff3G5TziAGkzrp0BIZaH2_Jtbug

###

##  Добавить предложение в избранное

POST http://localhost:6000/users/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NzI4NzljNmFmY2JmYWY4YjdjNDEzYWIiLCJpYXQiOjE3MzA3OTg2MTAsImV4cCI6MTczMDk3MTQxMH0.ovcfrRHJMTt1np5lff3G5TziAGkzrp0BIZaH2_Jtbug

{
  "offerId": "6727abe4326ef99e212e42f5"
}

###

## Удалить предложение из избранного

DELETE  http://localhost:6000/users/favorites/67152f430ace5d6726f44747 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NzI4NzljNmFmY2JmYWY4YjdjNDEzYWIiLCJpYXQiOjE3MzA3OTg2MTAsImV4cCI6MTczMDk3MTQxMH0.ovcfrRHJMTt1np5lff3G5TziAGkzrp0BIZaH2_Jtbug

###

## Отправить изображение

POST http://localhost:6000/users/62823cb2c5a64ce9f1b50eb6/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NzI4NzljNmFmY2JmYWY4YjdjNDEzYWIiLCJpYXQiOjE3MzA3OTg2MTAsImV4cCI6MTczMDk3MTQxMH0.ovcfrRHJMTt1np5lff3G5TziAGkzrp0BIZaH2_Jtbug

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatarPath"; filename="avatar-max.jpg"
Content-Type: image/jpeg

< /Users/ilakolmakov/508859-six-cities-8/markup/img/avatar-max.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
