# Аутентификация
## Регистрация нового пользователя

POST http://localhost:6000/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "ilkolmakov@yandex.ru",
  "userName": "IlyaK",
  "password": "qw12345678",
  "type": "pro"
}

###

## Авторизация пользователя

POST http://localhost:6000/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "ilkolmakov@yandex.ru",
  "password": "qw12345678"
}

###

## Проверить токен пользователя
GET http://localhost:6000/auth/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NzJiM2NiYmIwNjhiMmYwY2U5NWYwNTAiLCJpYXQiOjE3MzA4ODY4NDksImV4cCI6MTczMTA1OTY0OX0.TT5zxFnHQh0Y6K2WmHUxTDPZ9SmpYMzbkvwlHE21i5k

###