export const COMPONENT = {
  REST_APPLICATION: Symbol.for('kRestApplication'),
  LOGGER: Symbol.for('kLogger'),
  CONFIG: Symbol.for('kConfig'),
  DATABASE_CLIENT: Symbol.for('kDatabaseClient'),
  USER_SERVICE: Symbol.for('kUserService'),
  USER_MODEL: Symbol.for('kUserModel'),
  OFFER_SERVICE: Symbol.for('kOfferService'),
  OFFER_MODEL: Symbol.for('kOfferModel'),
  COMMENT_SERVICE: Symbol.for('kCommentService'),
  COMMENT_MODEL: Symbol.for('kCommentModel'),
  OFFER_CONTROLLER: Symbol.for('kOfferController'),
  EXCEPTION_FILTER: Symbol.for('kExceptionFilter'),
  USER_CONTROLLER: Symbol.for('kUserController'),
  COMMENT_CONTROLLER: Symbol.for('kCommentController'),
  AUTH_SERVICE: Symbol.for('kAuthService'),
  AUTH_CONTROLLER: Symbol.for('kAuthController'),
  AUTH_EXCEPTION_FILTER: Symbol.for('kAuthExceptionFilter'),
  HTTP_EXCEPTION_FILTER: Symbol.for('kHttpExceptionFilter'),
  VALIDATION_EXCEPTION_FILTER: Symbol.for('kValidationExceptionFilter'),
  PATH_TRANSFORMER: Symbol.for('kPathTransformer'),
} as const;
