# Предложения
## Получить список предложений
GET http://localhost:6000/offers HTTP/1.1
Content-Type: application/json

###

## Получить список предложений (ограниченное двумя элементами)
GET http://localhost:6000/offers?limit=2 HTTP/1.1
Content-Type: application/json

###

## Получить список премиальных предложений
GET http://localhost:6000/offers/premium?city=Paris HTTP/1.1
Content-Type: application/json

###

## Добавить новое предложение
POST http://localhost:6000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NzJhNmVhNTZlOWE4OTk0YjRiYzI5MzYiLCJpYXQiOjE3MzA4MzQxOTcsImV4cCI6MTczMTAwNjk5N30.e3m3JYV0OVdZYCKxT2fKMVGdfCu5UJv8fQ8EX47l57I

{
    "title": "Pullman Paris Tour Eiffel",
    "description": "The four-star Pullman Paris Tour Eiffel Hotel is located next to the Eiffel Tower on Trocadero Square.",
    "city": "Paris",
    "previewImg": "preview2.jpg",
    "images": ["photo1.jpg", "photo2.jpg", "photo3.jpg", "photo4.jpg", "photo5.jpg", "photo6.jpg"],
    "type": "hotel",
    "flatCount": 1,
    "guestCount": 4,
    "cost": 4000,
    "isPremium": false,
    "conveniences": ["Washer", "Towels", "Fridge"],
    "userId": "67152f430ace5d6726f44745",
    "coordinate": {
        "latitude": 52.370216,
        "longitude": 4.895168
    }
}


###

## Детальный просмотр предложения
GET http://localhost:6000/offers/672a728273590f2d5612140c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NzJhNmVhNTZlOWE4OTk0YjRiYzI5MzYiLCJpYXQiOjE3MzA4MzQxOTcsImV4cCI6MTczMTAwNjk5N30.e3m3JYV0OVdZYCKxT2fKMVGdfCu5UJv8fQ8EX47l57I

###

## Редактирование предложения
PATCH http://localhost:6000/offers/672a728273590f2d5612140c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NzI4NzljNmFmY2JmYWY4YjdjNDEzYWIiLCJpYXQiOjE3MzA3OTg2MTAsImV4cCI6MTczMDk3MTQxMH0.ovcfrRHJMTt1np5lff3G5TziAGkzrp0BIZaH2_Jtbug

{
  "title": "Cologne Country Lodge"
}

###

## Удаление предложения
DELETE http://localhost:6000/offers/672a6fc8a278429be5311997 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NzI4NzljNmFmY2JmYWY4YjdjNDEzYWIiLCJpYXQiOjE3MzA3OTg2MTAsImV4cCI6MTczMDk3MTQxMH0.ovcfrRHJMTt1np5lff3G5TziAGkzrp0BIZaH2_Jtbug

###